# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.  

scrape_configs:
  - job_name: 'monitorDjangoServer'
    static_configs:
      - targets: ["server:8002"]
        labels:
          group: 'monitoring_django'